# **NumPY**
NumPy stands for Numerical Python, is an open-source Python library that provides support for large, multi-dimensional arrays and matrices.

In [1]:
import numpy as np 
#impoprting numpy library

In [2]:
# 1D array without dtype
arr = np.array([3, 4, 7, 8, 10])
arr


array([ 3,  4,  7,  8, 10])

In [3]:
# will show the (rows, columns)
# columns will not be shown as it is 1D array
arr.shape

(5,)

In [4]:
# 2D array with dtype (i.e, maximun bits can be stored in a number)
arr2 = np.array([[3, 4, 7, 8, 10]], np.int32)   # 32 bits int can be stored only
arr2

array([[ 3,  4,  7,  8, 10]])

In [5]:
# print the dtype of array
arr2.dtype

dtype('int32')

In [6]:
# will show the (rows, columns)
# columns will be shown now as it is 2D array
arr2.shape

(1, 5)

In [7]:
# will show number of elements in the array
arr2.size

5

In [8]:
# will show number of dimensions
arr2.ndim

2

In [9]:
# finding how much bytes an array is consuming
arr2.nbytes

20

***Creation of numpy arrays***

In [10]:
# simple initialisation
arr = np.array([3, 4, 7, 8, 10])
arr

array([ 3,  4,  7,  8, 10])

In [11]:
# generating a random array
r = np.random.randint(100, size=40)
r

array([77, 16, 58,  3, 83, 42, 46, 39, 65, 39, 68, 84, 64, 14, 85, 54, 55,
       88,  2, 81, 33, 46, 60,  9, 33, 50, 22, 42,  2, 22, 42, 82, 58,  3,
        5, 64, 21, 13, 36, 71])

In [12]:
# Zero arrays (all elements are 0s)
zero_arr = np.zeros((5,2))  # (rows, colums)
zero_arr

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [13]:
# One's arrays (all elements are 1s)
one_arr = np.ones((5, 2))  # (rows, colums)
one_arr

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [14]:
# array in range, it will give 1D array
ran = np.arange(15)
ran

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [15]:
# using linspace, it will generate eqaul spaced elements
len = np.linspace(1, 20, 5)     # (starting, ending, number of elements)
len

array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ])

In [16]:
# genearting an identity matrix
id_mat = np.identity(5)
id_mat

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

***Reshaping an array***
- can be done only if old (rows\*columns) == new (rows\*columns)
- this doesn't affect the original array

In [17]:
# old array
ran

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [18]:
# newly shaped now
ran_matrix = ran.reshape(5, 3)
ran_matrix

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [19]:
# transpose of a matrix
ran_transpose = ran_matrix.T
ran_transpose

array([[ 0,  3,  6,  9, 12],
       [ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14]])

In [20]:
# converting N-D array to 1D
ran_1d = ran_matrix.ravel()
ran_1d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

***Axis***
- 1D arrays have only 1 axis i.e, axis 0
- 2D arrays have two axis i.e, axis 0, axis 1
    - axis 0 is that goes from upward to downward (columns)
    - axis 1 is that goes from left to right (rows)

In [21]:
# finding sum of columns
print(ran_matrix)
ran_matrix.sum(axis=0)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


array([30, 35, 40])

In [22]:
# finding sum of rows
print(ran_matrix)
ran_matrix.sum(axis=1)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


array([ 3, 12, 21, 30, 39])

In [23]:
# generating numpy array of random numbers
random = np.empty((4, 2))
random

array([[0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 8.71531799e-321],
       [1.24610723e-306, 1.29061142e-306]])

In [24]:
# interating every element of N-D array
for i in ran_matrix.flat:
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14


***Sortings in numpy array***

In [25]:
# gives index of each maximum element in axis=0
ran_matrix.argmax(axis=0)

array([4, 4, 4], dtype=int64)

In [26]:
# gives index of each maximum element in axis=1
ran_matrix.argmax(axis=1)

array([2, 2, 2, 2, 2], dtype=int64)

In [27]:
# gives index of maximum element in the array
ran_matrix.argmax()

14

In [28]:
# gives index of minimum element in the array
ran_matrix.argmin()

0

In [29]:
# gives index of each minimum element in axis=1
ran_matrix.argmin(axis=1)

array([0, 0, 0, 0, 0], dtype=int64)

In [30]:
# gives index of each minimum element in axis=0
ran_matrix.argmin(axis=0)

array([0, 0, 0], dtype=int64)

In [31]:
# gives indices of element in sorted manner in axis=0
ran_matrix.argsort(axis=0)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]], dtype=int64)

In [32]:
# gives indices of element in sorted manner in axis=1
ran_matrix.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [33]:
# gives the maximum element in the array
ran_matrix.max()

14

In [34]:
# gives the minimum element in the array
ran_matrix.min()

0

***Mathematical operations in numpy***

In [35]:
m1 = np.array([[4, 2, 5],
            [9, 1, 2],
            [3, 2, 8]])
m2 = np.array([[4, 3, 5],
            [5, 1, 1],
            [7, 2, 2]])

In [36]:
# addining two matrices
m1 + m2

array([[ 8,  5, 10],
       [14,  2,  3],
       [10,  4, 10]])

In [37]:
# subtracting two matrices
m1 - m2

array([[ 0, -1,  0],
       [ 4,  0,  1],
       [-4,  0,  6]])

In [38]:
# multiplication of two matrices (but it does elemeent wise)
m1*m2

array([[16,  6, 25],
       [45,  1,  2],
       [21,  4, 16]])

In [39]:
# multiplying a matrix with a constant
m1*2

array([[ 8,  4, 10],
       [18,  2,  4],
       [ 6,  4, 16]])

In [40]:
# geting square of all the elements
np.sqrt(m1)

array([[2.        , 1.41421356, 2.23606798],
       [3.        , 1.        , 1.41421356],
       [1.73205081, 1.41421356, 2.82842712]])

In [41]:
# functions like log, sin, exponential
print(np.exp(m1), "\n")
print(np.log(m1), "\n")
print(np.sin(m1))

[[5.45981500e+01 7.38905610e+00 1.48413159e+02]
 [8.10308393e+03 2.71828183e+00 7.38905610e+00]
 [2.00855369e+01 7.38905610e+00 2.98095799e+03]] 

[[1.38629436 0.69314718 1.60943791]
 [2.19722458 0.         0.69314718]
 [1.09861229 0.69314718 2.07944154]] 

[[-0.7568025   0.90929743 -0.95892427]
 [ 0.41211849  0.84147098  0.90929743]
 [ 0.14112001  0.90929743  0.98935825]]


In [42]:
# gives sum of all elements
m1.sum()

36

In [43]:
# finding elements greater than a value
np.where(m2>4)

# showing all the positions in m2 matrix where element is greater than 4

(array([0, 1, 2], dtype=int64), array([2, 0, 0], dtype=int64))

In [44]:
# counyts the number of non-zeros
np.count_nonzero(m1)

9

In [45]:
# gives positions of all non-zeros
np.nonzero(m1)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

***Logical operations in numpy***

In [47]:
data = np.array([1,2,3,4,5,6,7,8,9])
print(data>5)
print(data[data>5])

[False False False False False  True  True  True  True]
[6 7 8 9]
